{% set name = "evermore" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/evermore-{{ version }}.tar.gz
  sha256: a56b6321f0ed22c1eaeb2679baf2d7b12d0c9c8374486e46b11b97cfd4f6c2c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10
    - hatchling
    - pip
  run:
    - python >=3.10
    - jax
    - jaxlib
    - jaxtyping
    - equinox >=0.10.6

test:
  imports:
    - evermore
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pfackeldey/evermore
  summary: Differentiable (binned) likelihoods in JAX.
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://evermore.readthedocs.io/en/latest/
  dev_url: https://github.com/pfackeldey/evermore

extra:
  recipe-maintainers:
    - pfackeldey
